version: '3.1'

services:
  
  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: elasticsearch
    restart: always
    volumes: 
      - ./search_data:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  db:
    image: mysql:5.7.25
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=2677PFs8DWWNEn9M
    volumes:
      - ./mysql:/var/lib/mysql
      
  rails:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: tlcdirectory
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - SECRET_KEY_BASE=e9f0887b29e854a81e8dbdb3090b9a1b54ba2201c41b52966df6100ce672a70ed6c4c1a029ccb28cfc162a52ae2e68543b675eb5d4b703ecee903ebd8d66a6bb     
      - DATABASE_PASSWORD=2677PFs8DWWNEn9M
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - TERM=xterm
      - RAILS_ENV=production # replace with your current environment development or production
    volumes:
      - .:/home/tlcdirectory
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - elasticsearch      
      - db
      - selenium # development only
  
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    privileged: true
    ports:
      - '4444:4444'
      - '5900:5900'
    environment:
      - SCREEN_WIDTH=1440
      - SCREEN_HEIGHT=900
      - VNC_NO_PASSWORD=true
    logging:
      driver: none

